blog:
  title: Blog
  banner:
    title: Warning
    content: The blog will be down tomorrow.

# H2 설정
spring:
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true
#  mvc:
#    static-path-pattern: /resources/**